### ISSUE TITLE
Is auto-updating disabled?

### ISSUE THREAD

**Issue by ericmjl** [conda-forge/pyjanitor-feedstock#59]

**Comment by ericmjl** [comment]
Ugh, something went wrong -- not sure why my comment wasn't posted. Here's the original:

@ocefpaf apologies for bugging you about this, but I've noticed that conda-forge feedstock updates haven't been enabled on the pyjanitor feedstock. Has something changed recently?

**Comment by ocefpaf** [comment]
I believe we had an outage in the past few days due to some issues with Heroku but I'm travelling and I don't know the details. It seems that things are back online but, if not, please let us know.

**Comment by ocefpaf** [comment]
I believe we can close this one. Please re-open if this problem persists.
